// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_yf3TLU9mM1hgfVBlOLM5dgOMhDRLbRM',
    appId: '1:761926075595:web:82d878baa62dc47b76074e',
    messagingSenderId: '761926075595',
    projectId: 'eventually-user-d96c2',
    authDomain: 'eventually-user-d96c2.firebaseapp.com',
    storageBucket: 'eventually-user-d96c2.appspot.com',
    measurementId: 'G-01YJG3X581',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAil8aoK1TaTz4H8RmaWYyyYtNxVw8fQ5g',
    appId: '1:761926075595:android:2046655d64e9f87a76074e',
    messagingSenderId: '761926075595',
    projectId: 'eventually-user-d96c2',
    storageBucket: 'eventually-user-d96c2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA85vgbSsSB6DJBxin-U3IHuPBJjXyFBko',
    appId: '1:761926075595:ios:f03921e621cf2d9b76074e',
    messagingSenderId: '761926075595',
    projectId: 'eventually-user-d96c2',
    storageBucket: 'eventually-user-d96c2.appspot.com',
    iosClientId: '761926075595-jilmr859g2dff8f55n5i9k83ostiqnb2.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventuallyVendor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA85vgbSsSB6DJBxin-U3IHuPBJjXyFBko',
    appId: '1:761926075595:ios:f03921e621cf2d9b76074e',
    messagingSenderId: '761926075595',
    projectId: 'eventually-user-d96c2',
    storageBucket: 'eventually-user-d96c2.appspot.com',
    iosClientId: '761926075595-jilmr859g2dff8f55n5i9k83ostiqnb2.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventuallyVendor',
  );
}
