// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQQyZ_GGzaYVCEkSKv4AmwpZm6ObT6fT4',
    appId: '1:553503194545:web:311ddeb0db49db33ff1190',
    messagingSenderId: '553503194545',
    projectId: 'eventually-vendor',
    authDomain: 'eventually-vendor.firebaseapp.com',
    storageBucket: 'eventually-vendor.appspot.com',
    measurementId: 'G-C586KFNGW1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKdsFYC1GCL4WL26550DAVnE01kfax4D0',
    appId: '1:553503194545:android:80ba68079d7c7406ff1190',
    messagingSenderId: '553503194545',
    projectId: 'eventually-vendor',
    storageBucket: 'eventually-vendor.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeniXZ_vJIpE2HS7JLv6-o_w1_tPiAG_s',
    appId: '1:553503194545:ios:1f4a1df9562835a5ff1190',
    messagingSenderId: '553503194545',
    projectId: 'eventually-vendor',
    storageBucket: 'eventually-vendor.appspot.com',
    androidClientId: '553503194545-1bhibb68trhdhde9lng19dqni07pblhn.apps.googleusercontent.com',
    iosClientId: '553503194545-tiqehnd8kmt90rbnprfcv77ehiln29if.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventuallyVendor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeniXZ_vJIpE2HS7JLv6-o_w1_tPiAG_s',
    appId: '1:553503194545:ios:1f4a1df9562835a5ff1190',
    messagingSenderId: '553503194545',
    projectId: 'eventually-vendor',
    storageBucket: 'eventually-vendor.appspot.com',
    androidClientId: '553503194545-1bhibb68trhdhde9lng19dqni07pblhn.apps.googleusercontent.com',
    iosClientId: '553503194545-tiqehnd8kmt90rbnprfcv77ehiln29if.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventuallyVendor',
  );
}
